version: 2.1
orbs:
  matlab: mathworks/matlab@dev:alpha
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: "disp('hi'); disp('wow');"
      - matlab/run-tests: 
          test-results-junit: results.xml
      - store_test_results:
          path: results.xml
      - store_artifacts:
         path: results.xml
