version: 2.1
orbs:
  matlab: mathworks/matlab@0.1.4
 #codecov: codecov/codecov@1.1.1
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests: 
          code-coverage-cobertura: coverage.xml
      - coveralls/upload
      #    path_to_lcov: coverage.xml
      #- codecov/upload: 
      #    file: coverage.xml
     
