version: 2.1
orbs:
  matlab: mathworks/matlab@0.4.0
  codecov: codecov/codecov@1.1.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - matlab/install
      - matlab/run-tests: 
          code-coverage-cobertura: coverage.xml
      - codecov/upload: 
          file: coverage.xml
